[project]
name = "currency-assistant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.16.4",
    "celery>=5.5.3",
    "fastapi>=0.116.1",
    "httpx>=0.28.1",
    "numpy>=2.3.2",
    "pandas>=2.3.2",
    "psycopg2-binary>=2.9.10",
    "pydantic-settings>=2.10.1",
    "pydantic[email]>=2.11.7",
    "redis>=6.4.0",
    "scikit-learn>=1.7.1",
    "sqlalchemy>=2.0.43",
    "torch>=2.8.0",
    "uvicorn[standard]>=0.35.0",
]
